
# import Org from 'org.gql'
# import User from 'user.gql'
# import Role from 'role.gql'

type Query {
    org(query: OrgInput): OrgOutput
    user(query: UserInput): UserOutput
    role(query: RoleInput): RoleOutput
}

