# import User from 'user.gql'
# import Role from 'role.gql'

type UserRole {
    user: User
    role: Role
}
input UserRoleInput {
    user: UserInput
    role: RoleInput
}
input UserRoleRecordInput {
    user: UserInput
    role: RoleInput
}
type UserRoleOutput {
    count: Int
    data: [UserRole]
}